assemblies:
    canu: data/canu.fa
    canu_racon1: data/canu_racon1.fa
    canu_racon2: data/canu_racon2.fa
    canu_racon2_pilon1: data/canu_racon2_pilon1.fa
    canu_racon2_pilon2: data/canu_racon2_pilon2.fa
    canu_racon2_polca1: data/canu_racon2_polca1.fa
    flye_corrected: data/flye_corrected.fa
    flye_corrected_racon1: data/flye_corrected_racon1.fa
    flye_corrected_racon2: data/flye_corrected_racon2.fa
    flye_corrected_racon2_pilon1: data/flye_corrected_racon2_pilon1.fa
    flye_corrected_racon2_polca1: data/flye_corrected_racon2_polca1.fa
    flye_raw: data/flye_raw.fa
    flye_raw_racon1: data/flye_raw_racon1.fa
    flye_raw_racon2: data/flye_raw_racon2.fa
    flye_raw_racon2_pilon1: data/flye_raw_racon2_pilon1.fa
    flye_raw_racon2_polca1: data/flye_raw_racon2_polca1.fa
    flye_trimmed: data/flye_trimmed.fa
    flye_trimmed_racon1: data/flye_trimmed_racon1.fa
    flye_trimmed_racon2: data/flye_trimmed_racon2.fa
    flye_trimmed_racon2_pilon1: data/flye_trimmed_racon2_pilon1.fa
    flye_trimmed_racon2_polca1: data/flye_trimmed_racon2_polca1.fa
    wtdbg2_corrected: data/wtdbg2_corrected.fa
    wtdbg2_corrected_racon1: data/wtdbg2_corrected_racon1.fa
    wtdbg2_corrected_racon2: data/wtdbg2_corrected_racon2.fa
    wtdbg2_corrected_racon2_pilon1: data/wtdbg2_corrected_racon2_pilon1.fa
    wtdbg2_corrected_racon2_polca1: data/wtdbg2_corrected_racon2_polca1.fa
    wtdbg2_raw: data/wtdbg2_raw.fa
    wtdbg2_raw_racon1: data/wtdbg2_raw_racon1.fa
    wtdbg2_raw_racon2: data/wtdbg2_raw_racon2.fa
    wtdbg2_raw_racon2_pilon1: data/wtdbg2_raw_racon2_pilon1.fa
    wtdbg2_raw_racon2_polca1: data/wtdbg2_raw_racon2_polca1.fa
    wtdbg2_trimmed: data/wtdbg2_trimmed.fa
    wtdbg2_trimmed_racon1: data/wtdbg2_trimmed_racon1.fa
    wtdbg2_trimmed_racon2: data/wtdbg2_trimmed_racon2.fa
    wtdbg2_trimmed_racon2_pilon1: data/wtdbg2_trimmed_racon2_pilon1.fa
    wtdbg2_trimmed_racon2_polca1: data/wtdbg2_trimmed_racon2_polca1.fa

busco:
    mode: 'genome'
    threads: 24
    memory: 64000
    runtime: '1-00:00:00'
    extra: ''

stats:
    memory: 2000
    runtime: '0-0:15:00'
